package theknife.network;

public enum RequestType {
    LOGIN,
    REGISTER,
    SEARCH,
    GET_DETTAGLIO,
    ADD_REVIEW,
    EDIT_REVIEW,
    DELETE_REVIEW,
    ADD_FAVORITE,
    REMOVE_FAVORITE,
    GET_FAVORITES,
    ADD_RESTAURANT,
    REPLY_REVIEW,
    GET_SUMMARY,
    CHANGE_PASSWORD,
    RESET_PASSWORD
}